# Generated by Django 4.1.7 on 2023-05-04 05:50

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CMSUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('createdBy', models.CharField(max_length=200)),
                ('modifiedBy', models.CharField(max_length=200)),
                ('createdat', models.DateTimeField(auto_now_add=True, db_column='createdAt', null=True)),
                ('updatedat', models.DateTimeField(auto_now=True, db_column='updatedAt', null=True)),
            ],
            options={
                'verbose_name_plural': 'User',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupName', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('createdBy', models.CharField(max_length=200)),
                ('modifiedBy', models.CharField(max_length=200)),
                ('createdat', models.DateTimeField(auto_now_add=True, db_column='createdAt', null=True)),
                ('updatedat', models.DateTimeField(auto_now=True, db_column='updatedAt', null=True)),
            ],
            options={
                'verbose_name_plural': 'Group',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menuName', models.CharField(max_length=200)),
                ('menuLink', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('createdBy', models.CharField(max_length=200)),
                ('modifiedBy', models.CharField(max_length=200)),
                ('createdat', models.DateTimeField(auto_now_add=True, db_column='createdAt', null=True)),
                ('updatedat', models.DateTimeField(auto_now=True, db_column='updatedAt', null=True)),
            ],
            options={
                'verbose_name_plural': 'Menu',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roleName', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('createdBy', models.CharField(max_length=200)),
                ('modifiedBy', models.CharField(max_length=200)),
                ('createdat', models.DateTimeField(auto_now_add=True, db_column='createdAt', null=True)),
                ('updatedat', models.DateTimeField(auto_now=True, db_column='updatedAt', null=True)),
            ],
            options={
                'verbose_name_plural': 'Role',
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdat', models.DateTimeField(auto_now_add=True, db_column='createdAt', null=True)),
                ('updatedat', models.DateTimeField(auto_now=True, db_column='updatedAt', null=True)),
                ('cmUserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MasterUser.cmsuser')),
                ('roleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MasterUser.role')),
            ],
            options={
                'verbose_name_plural': 'UserRole',
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contentTitle', models.CharField(max_length=200)),
                ('contentImage', models.ImageField(upload_to='upload/content/')),
                ('contentData', tinymce.models.HTMLField()),
                ('active', models.BooleanField(default=True)),
                ('createdBy', models.CharField(max_length=200)),
                ('modifiedBy', models.CharField(max_length=200)),
                ('createdat', models.DateTimeField(auto_now_add=True, db_column='createdAt', null=True)),
                ('updatedat', models.DateTimeField(auto_now=True, db_column='updatedAt', null=True)),
                ('menuID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MasterUser.menu')),
            ],
            options={
                'verbose_name_plural': 'Content',
            },
        ),
    ]
