# Generated by Django 4.1.7 on 2023-05-04 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MasterUser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdat', models.DateTimeField(auto_now_add=True, db_column='createdAt', null=True)),
                ('updatedat', models.DateTimeField(auto_now=True, db_column='updatedAt', null=True)),
                ('cmUserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MasterUser.cmsuser')),
                ('groupID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MasterUser.group')),
            ],
            options={
                'verbose_name_plural': 'UserGroup',
            },
        ),
    ]
