# Generated by Django 4.1.7 on 2023-05-04 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MasterUser', '0002_usergroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdat', models.DateTimeField(auto_now_add=True, db_column='createdAt', null=True)),
                ('updatedat', models.DateTimeField(auto_now=True, db_column='updatedAt', null=True)),
                ('groupID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MasterUser.group')),
                ('menuID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MasterUser.menu')),
            ],
            options={
                'verbose_name_plural': 'GroupMenu',
            },
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdat', models.DateTimeField(auto_now_add=True, db_column='createdAt', null=True)),
                ('updatedat', models.DateTimeField(auto_now=True, db_column='updatedAt', null=True)),
                ('userGroupID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MasterUser.usergroup')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MasterUser.cmsuser')),
                ('userMenuID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MasterUser.groupmenu')),
                ('userRoleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MasterUser.userrole')),
            ],
            options={
                'verbose_name_plural': 'Details',
            },
        ),
    ]
