# Generated by Django 4.1.7 on 2023-05-09 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MasterUser', '0003_groupmenu_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='menuLink',
        ),
        migrations.DeleteModel(
            name='Detail',
        ),
    ]
