# Generated by Django 4.1.7 on 2023-05-30 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MasterUser', '0009_events_expiration_date_trends_expiration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='expiration_date',
            field=models.DateTimeField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='expiration_date',
            field=models.DateTimeField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='newupdates',
            name='expiration_date',
            field=models.DateTimeField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='studentnoticeboard',
            name='expiration_date',
            field=models.DateTimeField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='trends',
            name='expiration_date',
            field=models.DateTimeField(default='', max_length=100),
        ),
    ]
