# Generated by Django 4.1.7 on 2023-05-31 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MasterUser', '0011_alter_studentnoticeboard_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampusGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdat', models.DateTimeField(auto_now_add=True, db_column='createdAt', null=True)),
                ('updatedat', models.DateTimeField(auto_now=True, db_column='updatedAt', null=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MasterUser.campus')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MasterUser.group')),
            ],
        ),
    ]
