# Generated by Django 4.1.7 on 2023-06-01 13:02

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('MasterUser', '0013_remove_events_contents_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyProfiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('Image', models.ImageField(upload_to='upload/faculty/')),
                ('designation', models.CharField(max_length=200)),
                ('jouralPublications', models.IntegerField()),
                ('conferencePublications', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=200)),
                ('fax', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('description', tinymce.models.HTMLField()),
                ('createdat', models.DateTimeField(auto_now_add=True, db_column='createdAt', null=True)),
                ('updatedat', models.DateTimeField(auto_now=True, db_column='updatedAt', null=True)),
            ],
            options={
                'verbose_name_plural': 'Faculty',
            },
        ),
    ]
