# Generated by Django 4.1.7 on 2023-06-01 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MasterUser', '0014_facultyprofiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(default='', upload_to='upload/tender/')),
                ('createdat', models.DateTimeField(auto_now_add=True, db_column='createdAt', null=True)),
                ('updatedat', models.DateTimeField(auto_now=True, db_column='updatedAt', null=True)),
                ('expiration_date', models.DateTimeField(default='', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Tender',
            },
        ),
        migrations.DeleteModel(
            name='Trends',
        ),
    ]
