# Generated by Django 4.1.7 on 2023-06-11 14:26

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('MasterUser', '0015_tender_delete_trends'),
    ]

    operations = [
        migrations.AddField(
            model_name='childdepartment',
            name='deptDescription',
            field=tinymce.models.HTMLField(default='N/A'),
        ),
    ]
